#!/bin/bash

echo "Running aliasmate setup script..."

# Ensure the .alias_mate directory exists for the user
if [ ! -d "$HOME/.alias_mate" ]; then
    echo "Creating directory: $HOME/.alias_mate"
    mkdir -p "$HOME/.alias_mate"
fi

echo "Run 'aliasmate --help' to get started"
